auth:
  image: "logankoester/wordpress-oauth2-proxy"
  ports:
    - "80:80"
    - "443:443"
  environment:
    HOST: "private_service.example.com"
    TARGET_URI: "private_service"
    TARGET_SCHEME: "http"
    DB_URI: "mongodb://mongo/auth"
    SESSION_SECRET: "SOME RANDOM STRING"
    OAUTH_CLIENT_ID: "YOUR CLIENT ID FROM WORDPRESS"
    OAUTH_CLIENT_SECRET: "YOUR CLIENT SECRET FROM WORDPRESS"
    OAUTH_URL: "YOUR WORDPRESS SITEURL"
    OAUTH_CALLBACK_URL: "https://private_service.example.com/auth/wordpress/callback"
    HTTPS_FORCE: false
    KEY_FILE: "server.key"
    CERT_FILE: "server.crt"
  links:
    - "mongo"
    - "private_service"
  volumes:
    - "server.key:/usr/src/wordpress-oauth2-proxy/server.key:ro"
    - "server.crt:/usr/src/wordpress-oauth2-proxy/server.crt:ro"

mongo:
  image: "mongo"

private_service:
  image: "YOUR PRIVATE SERVICE"
  expose:
    - "80"
